receptors_dir: Data/Receptors
ligand_dirs:
- Data/Ligands/JKU/pdbqt
diffdock_dir: /home/manndo/docking_tools/DiffDock
diffdock_python: /home/manndo/anaconda3/envs/diffdock/bin/python
diffdock_conda_env: diffdock
num_samples: 10
inference_steps: 20
device: cuda:0
timeout_per_complex: 600
output_dir: Dockings/diffdock_results
log_dir: Dockings/Logs/diffdock_logs
batch_mode: true
batch_size: 15
group_by_receptor: true
max_workers: 1
overwrite_existing: false
overwrite_error_log: false
optimization: gnina
optimize_search: minimize
optimize_autobox_add: 4.0
optimize_cpu: 1
optimize_seed: 0
optimize_timeout: 300
gnina_use_gpu: true
smina_executable: /home/manndo/anaconda3/envs/diffdock/bin/smina
gnina_executable: /home/manndo/docking_tools/gnina
gnina_lib_dirs: []
