#!/usr/bin/env python
"""
PyMOL Box Parameter Calculator for AutoDock Vina
Calculates box center and size from ligand or binding site residues
"""

from pymol import cmd, stored
import sys

def calculate_box_parameters(selection, padding=5.0):
    """
    Calculate docking box center and size from a PyMOL selection.
    
    Parameters:
    -----------
    selection : str
        PyMOL selection string (e.g., 'resn LIG' or 'resi 50-70')
    padding : float
        Additional padding to add to box size in Angstroms (default: 5.0)
    
    Returns:
    --------
    dict : Dictionary containing center (x,y,z) and size (x,y,z)
    """
    
    # Check if selection exists
    if cmd.count_atoms(selection) == 0:
        print(f"ERROR: No atoms found in selection '{selection}'")
        return None
    
    # Get bounding box coordinates
    coords = cmd.get_extent(selection)
    
    # Calculate center coordinates
    center_x = (coords[0][0] + coords[1][0]) / 2.0
    center_y = (coords[0][1] + coords[1][1]) / 2.0
    center_z = (coords[0][2] + coords[1][2]) / 2.0
    
    # Calculate box dimensions
    size_x = abs(coords[1][0] - coords[0][0]) + padding
    size_y = abs(coords[1][1] - coords[0][1]) + padding
    size_z = abs(coords[1][2] - coords[0][2]) + padding
    
    # Store results
    results = {
        'center': [center_x, center_y, center_z],
        'size': [size_x, size_y, size_z],
        'padding': padding,
        'num_atoms': cmd.count_atoms(selection)
    }
    
    return results


def print_box_params(results):
    """Print box parameters in multiple formats"""
    
    if results is None:
        return
    
    center = results['center']
    size = results['size']
    
    print("\n" + "="*60)
    print("DOCKING BOX PARAMETERS")
    print("="*60)
    print(f"Selection contains: {results['num_atoms']} atoms")
    print(f"Padding applied: {results['padding']} Å")
    print()
    
    print("Box Center:")
    print(f"  X = {center[0]:.3f}")
    print(f"  Y = {center[1]:.3f}")
    print(f"  Z = {center[2]:.3f}")
    print()
    
    print("Box Size:")
    print(f"  X = {size[0]:.3f} Å")
    print(f"  Y = {size[1]:.3f} Å")
    print(f"  Z = {size[2]:.3f} Å")
    print()
    
    print("-" * 60)
    print("FOR AUTODOCK VINA CONFIG FILE:")
    print("-" * 60)
    print(f"center_x = {center[0]:.3f}")
    print(f"center_y = {center[1]:.3f}")
    print(f"center_z = {center[2]:.3f}")
    print(f"size_x = {size[0]:.1f}")
    print(f"size_y = {size[1]:.1f}")
    print(f"size_z = {size[2]:.1f}")
    print()
    
    print("-" * 60)
    print("FOR mk_prepare_receptor.py COMMAND:")
    print("-" * 60)
    print(f"--box_center {center[0]:.3f} {center[1]:.3f} {center[2]:.3f} \\")
    print(f"--box_size {size[0]:.1f} {size[1]:.1f} {size[2]:.1f}")
    print()
    
    print("-" * 60)
    print("FOR VINA COMMAND LINE:")
    print("-" * 60)
    print(f"--center_x {center[0]:.3f} --center_y {center[1]:.3f} --center_z {center[2]:.3f} \\")
    print(f"--size_x {size[0]:.1f} --size_y {size[1]:.1f} --size_z {size[2]:.1f}")
    print("="*60 + "\n")


def save_config_file(results, filename="vina_config.txt"):
    """Save box parameters to Vina config file"""
    
    if results is None:
        return
    
    center = results['center']
    size = results['size']
    
    with open(filename, 'w') as f:
        f.write("# AutoDock Vina configuration file\n")
        f.write("# Generated by PyMOL box calculator\n\n")
        f.write(f"center_x = {center[0]:.3f}\n")
        f.write(f"center_y = {center[1]:.3f}\n")
        f.write(f"center_z = {center[2]:.3f}\n\n")
        f.write(f"size_x = {size[0]:.1f}\n")
        f.write(f"size_y = {size[1]:.1f}\n")
        f.write(f"size_z = {size[2]:.1f}\n\n")
        f.write("# Add additional parameters below:\n")
        f.write("# receptor = receptor.pdbqt\n")
        f.write("# ligand = ligand.pdbqt\n")
        f.write("# exhaustiveness = 32\n")
        f.write("# num_modes = 20\n")
    
    print(f"Config file saved to: {filename}")


def save_box_file(results, filename="box.txt"):
    """Save minimal Vina-style box file (center_x/center_y/center_z/size_x/size_y/size_z)."""
    if results is None:
        return
    center = results['center']
    size = results['size']
    with open(filename, 'w') as f:
        f.write(f"center_x = {center[0]:.3f}\n")
        f.write(f"center_y = {center[1]:.3f}\n")
        f.write(f"center_z = {center[2]:.3f}\n")
        f.write(f"size_x = {size[0]:.1f}\n")
        f.write(f"size_y = {size[1]:.1f}\n")
        f.write(f"size_z = {size[2]:.1f}\n")
    print(f"Box file saved to: {filename}")


def visualize_box(results, name="docking_box"):
    """Create a visual representation of the docking box in PyMOL"""
    
    if results is None:
        return
    # Lazy import CGO constants to avoid import issues outside PyMOL
    try:
        import importlib
        cgo = importlib.import_module('pymol.cgo')
        CGO_BEGIN, CGO_LINES, CGO_COLOR, CGO_VERTEX, CGO_END = (
            getattr(cgo, 'BEGIN'), getattr(cgo, 'LINES'), getattr(cgo, 'COLOR'), getattr(cgo, 'VERTEX'), getattr(cgo, 'END')
        )
    except Exception:
        print("ERROR: PyMOL CGO is not available; cannot visualize the box.")
        return
    
    center = results['center']
    size = results['size']
    
    # Calculate box corners
    x_min = center[0] - size[0]/2
    x_max = center[0] + size[0]/2
    y_min = center[1] - size[1]/2
    y_max = center[1] + size[1]/2
    z_min = center[2] - size[2]/2
    z_max = center[2] + size[2]/2
    
    # Create CGO box object
    box = [
        CGO_BEGIN, CGO_LINES,
        CGO_COLOR, 1.0, 1.0, 0.0,  # Yellow color
        
        # Bottom face
        CGO_VERTEX, x_min, y_min, z_min,
        CGO_VERTEX, x_max, y_min, z_min,
        CGO_VERTEX, x_max, y_min, z_min,
        CGO_VERTEX, x_max, y_max, z_min,
        CGO_VERTEX, x_max, y_max, z_min,
        CGO_VERTEX, x_min, y_max, z_min,
        CGO_VERTEX, x_min, y_max, z_min,
        CGO_VERTEX, x_min, y_min, z_min,
        
        # Top face
        CGO_VERTEX, x_min, y_min, z_max,
        CGO_VERTEX, x_max, y_min, z_max,
        CGO_VERTEX, x_max, y_min, z_max,
        CGO_VERTEX, x_max, y_max, z_max,
        CGO_VERTEX, x_max, y_max, z_max,
        CGO_VERTEX, x_min, y_max, z_max,
        CGO_VERTEX, x_min, y_max, z_max,
        CGO_VERTEX, x_min, y_min, z_max,
        
        # Vertical edges
        CGO_VERTEX, x_min, y_min, z_min,
        CGO_VERTEX, x_min, y_min, z_max,
        CGO_VERTEX, x_max, y_min, z_min,
        CGO_VERTEX, x_max, y_min, z_max,
        CGO_VERTEX, x_max, y_max, z_min,
        CGO_VERTEX, x_max, y_max, z_max,
        CGO_VERTEX, x_min, y_max, z_min,
        CGO_VERTEX, x_min, y_max, z_max,
        
        CGO_END
    ]
    
    # Load box into PyMOL
    cmd.load_cgo(box, name)
    
    # Create pseudoatom at center
    cmd.pseudoatom(f"{name}_center", pos=center)
    cmd.show("spheres", f"{name}_center")
    cmd.color("red", f"{name}_center")
    
    print(f"Box visualization created: {name}")
    print(f"Box center marked: {name}_center")


def get_box_from_ligand(ligand_selection="resn LIG", padding=5.0, 
                        visualize=True, save_config=True):
    """
    Complete workflow: calculate, display, save, and visualize box from ligand
    
    Parameters:
    -----------
    ligand_selection : str
        PyMOL selection for ligand (default: 'resn LIG')
    padding : float
        Padding around ligand in Angstroms (default: 5.0)
    visualize : bool
        Create visual box in PyMOL (default: True)
    save_config : bool
        Save config file to disk (default: True)
    """
    
    # Convert padding to float if it's a string (from command line)
    if isinstance(padding, str):
        padding = float(padding)
    
    # Convert visualize and save_config to bool if they're strings
    if isinstance(visualize, str):
        visualize = visualize.lower() in ('true', '1', 'yes')
    if isinstance(save_config, str):
        save_config = save_config.lower() in ('true', '1', 'yes')
    
    # Calculate parameters
    results = calculate_box_parameters(ligand_selection, padding)
    
    if results is None:
        return None
    
    # Print results
    print_box_params(results)
    
    # Save config file
    if save_config:
        save_config_file(results)
    
    # Visualize box
    if visualize:
        visualize_box(results)
    
    return results


def get_box_from_residues(residue_list, padding=5.0, visualize=True, save_config=True):
    """
    Calculate box from binding site residues
    
    Parameters:
    -----------
    residue_list : str or list
        Residue selection (e.g., 'resi 50-70' or 'resi 50+52+55+60-70')
    padding : float
        Padding around residues in Angstroms (default: 5.0)
    """
    
    # Convert padding to float if it's a string
    if isinstance(padding, str):
        padding = float(padding)
    
    # Convert visualize and save_config to bool if they're strings
    if isinstance(visualize, str):
        visualize = visualize.lower() in ('true', '1', 'yes')
    if isinstance(save_config, str):
        save_config = save_config.lower() in ('true', '1', 'yes')
    
    selection = residue_list if isinstance(residue_list, str) else f"resi {'+'.join(map(str, residue_list))}"
    
    results = calculate_box_parameters(selection, padding)
    
    if results is None:
        return None
    
    print_box_params(results)
    
    if save_config:
        save_config_file(results)
    
    if visualize:
        visualize_box(results)
    
    return results


def get_box_from_receptor(receptor_object="receptor", selection=None, padding=5.0,
                          visualize=True, save_box=True, filename="box.txt"):
    """Calculate box from a receptor object (optionally a sub-selection) and write box.txt.

    Parameters:
    -----------
    receptor_object : str
        Name of the receptor object loaded in PyMOL (default: 'receptor').
    selection : str | None
        Optional PyMOL selection string relative to the receptor object, e.g., 'resi 50-70' or 'chain A'.
        If provided, the effective selection is f"({receptor_object}) and ({selection})".
        If None, the entire receptor object is used.
    padding : float
        Padding (Angstroms) added to the computed extents for the box dimensions (default: 5.0).
    visualize : bool
        Whether to visualize the box in PyMOL (default: True).
    save_box : bool
        Whether to save a minimal 'box.txt' file with center and size (default: True).
    filename : str
        Target filename for the box file (default: 'box.txt').

    Returns:
    --------
    dict | None: results dictionary with 'center' and 'size' or None on failure.
    """

    # Build selection for calculation
    obj_sel = f"({receptor_object})"
    eff_sel = obj_sel if not selection else f"{obj_sel} and ({selection})"

    # Calculate parameters
    results = calculate_box_parameters(eff_sel, padding)
    if results is None:
        return None

    # Print for convenience
    print_box_params(results)

    # Save minimal box.txt if requested
    if save_box:
        save_box_file(results, filename=filename)

    # Visualize if requested
    if visualize:
        visualize_box(results, name="docking_box")

    return results



# Register functions as PyMOL commands
cmd.extend("get_box_from_ligand", get_box_from_ligand)
cmd.extend("get_box_from_residues", get_box_from_residues)
cmd.extend("get_box_from_receptor", get_box_from_receptor)
cmd.extend("visualize_box", visualize_box)


# If running as standalone script
if __name__ == "__main__":
    print("PyMOL Box Calculator loaded successfully!")
    print("\nAvailable commands:")
    print("  get_box_from_ligand [selection] [padding]")
    print("  get_box_from_residues [residue_selection] [padding]")
    print("\nExample usage:")
    print("  get_box_from_ligand resn LIG, 5.0")
    print("  get_box_from_residues resi 50-70, 8.0")
